### ISSUE TITLE
Bug: javafx implementation of SetProperty causes exception

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mlieshoff/exactor#32]
```
ava.lang.InstantiationException
at 
sun.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(Instantiat
ionExceptionConstructorAccessorImpl.java:48)
at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
at java.lang.Class.newInstance(Class.java:374)
at 
com.exoftware.exactor.ExecutionSet.createCommandInstance(ExecutionSet.java:274)
at com.exoftware.exactor.ExecutionSet.findCommandClass(ExecutionSet.java:264)
at com.exoftware.exactor.ExecutionSet.findCommand(ExecutionSet.java:200)
at 
com.exoftware.exactor.parser.ScriptParser.createCommand(ScriptParser.java:132)
at 
com.exoftware.exactor.parser.ScriptParser.createCommandFromLine(ScriptParser.jav
a:124)
at com.exoftware.exactor.parser.ScriptParser.parseLine(ScriptParser.java:110)
at com.exoftware.exactor.parser.ScriptParser.parse(ScriptParser.java:101)
at 
com.exoftware.exactor.ExecutionSet.createCompositeInstance(ExecutionSet.java:286
)
at com.exoftware.exactor.ExecutionSet.findCommand(ExecutionSet.java:198)
at 
com.exoftware.exactor.parser.ScriptParser.createCommand(ScriptParser.java:132)
at 
com.exoftware.exactor.parser.ScriptParser.createCommandFromLine(ScriptParser.jav
a:124)
at com.exoftware.exactor.parser.ScriptParser.parseLine(ScriptParser.java:110)
at com.exoftware.exactor.parser.ScriptParser.parse(ScriptParser.java:101)
at com.exoftware.exactor.Runner.run(Runner.java:126)
at com.smeet.act.ACT.proceed(ACT.java:178)
at com.smeet.act.ACT.test(ACT.java:101)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at 
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.jav
a:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at junit.framework.TestCase.runTest(TestCase.java:168)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at 
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.jav
a:43)
```

Original issue reported on code.google.com by `michael....@smeet.com` on 12 Nov 2014 at 2:11

**Comment by mlieshoff** [comment]
set system property "exactor.blacklisted.classes" to define comma-separated full specified names of classes, case-sensitiv.
